version: "3.9"
x-common:
  &x-common
  image: range3/chfs:master
  init: true
  networks:
    chfs_net:
  cap_add:
    - SYS_PTRACE
  security_opt:
    - seccomp:unconfined
  privileged: true
  extra_hosts:
    - c0:172.30.0.2
    - c1:172.30.0.3

services:
  chfsd0:
    <<: *x-common
    image: range3/chfs:master
    ports:
      - "50000:50000"
    networks:
      chfs_net:
        ipv4_address: 172.30.0.2
    command: chfsd -d -p ofi+sockets -h 172.30.0.2:50000
  chfsd1:
    <<: *x-common
    depends_on:
      - chfsd0
    image: range3/chfs:master
    ports:
      - "50001:50000"
    networks:
      chfs_net:
        ipv4_address: 172.30.0.3
    command: chfsd -d -p ofi+sockets -h 172.30.0.3:50000 ofi+sockets://172.30.0.2:50000

networks:
  chfs_net:
    name: chfs_net
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 172.30.0.0/16
