name: Docker Publish

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - 
        name: Docker Meta
        id: docker-meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: |
            ${{ github.repository_owner }}/chfs
            ghcr.io/${{ github.repository_owner }}/chfs
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and push
        uses: docker/build-push-action@v2.2.0
        with:
          context: .
          file: Dockerfile
          build-args: CHFS_SRC_SPACK_ENV=${{ github.ref_name == 'master' && 'chfs-master' || 'chfs' }}
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker-meta.outputs.tags }}
          labels: ${{ steps.docker-meta.outputs.labels }}
          cache-from: type=registry,ref=${{ github.repository_owner }}/chfs:buildcache
          cache-to: type=registry,ref=${{ github.repository_owner }}/chfs:buildcache,mode=max
